library(affy)

source("rma.R")
source("mas5.R")
source("images.R")
source("heatmap.R")
source("boxplot.R")
source("signalkurve.R")
source("correlation.R")
source("RNAdegradation.R")
source("table2.R")
source("scatterPlot.R")